### ISSUE TITLE
Extract final draft text (23 Oct) to markdown

### ISSUE THREAD

**Issue by rufuspollock** [rgrp/cop21#2]
Convert [10 nov draft final negotiating text (pdf)](http://unfccc.int/resource/docs/2015/adp2/eng/11infnot.pdf) to markdown. Want a clean, markdowned, txt version in `/23-oct-2015/index.md`

**This is being actively worked on here: https://github.com/okfn/cop21/blob/gh-pages/23-oct-2015/index.md**

We extracted from the word version: https://unfccc.int/files/bodies/awg/application/vnd.openxmlformats-officedocument.wordprocessingml.document/ws_1_and_2_2330_.docx using pandoc and then started fixing formatting.

**We need help**:
- tidying up the markdown.
- checking against [10 nov revised version](http://unfccc.int/resource/docs/2015/adp2/eng/11infnot.pdf) (we started with word doc of 23 oct text - the latest word doc we could find)

**If you are interested in helping:**
- we suggest doing an article of the treaty at a time.
- please drop a comment here saying which article you plan to work on before you start work and then notify as soon as you've done it.
- be very careful if editing through the online editor to reload the page to have the absolute latest version
- please structure the markdown "semantically" - we care more about getting proper html lists than that the lists have the right format.
  - our goal is not to slavishly reproduce the exact layout / look of the PDF but rather to capture all the semantic structure. Thus, for example, we are move some headings into the order list headings - see [article 3](http://cop21.okfnlabs.org/23-oct-2015/#article-3-mitigation) for example.

**Question: should we split the "Decision" from the "Agreement" - i'm inclined to say yes**
## Background

Suggest we go for markdown version with jekyll frontmatter. Pagination is a bit complex but may not matter.

I tried pdftotext and it was ok but pretty ugly - could commit and then invite folks to help clean up.

**Comment by rufuspollock** [comment]
This is being actively worked on here: https://github.com/okfn/cop21/blob/gh-pages/23-oct-2015/index.md

**Comment by Snekili** [comment]
Working on Article 4, 5, 6, 7, 8

**Comment by Snekili** [comment]
Article

**Comment by rufuspollock** [comment]
FIXED.
- http://cop21.okfnlabs.org/agreement
- http://cop21.okfnlabs.org/decision/
