### ISSUE TITLE
New background image

### ISSUE THREAD

**Issue by rgieseke** [rgrp/cop21#31]
Hi,

I looked a bit into replacing the default background image with some stitched together Public Domain images from the COP21 Flickr stream.

![screenshot_2016-04-25_15-46-10](https://cloud.githubusercontent.com/assets/198537/14785915/177417b8-0afd-11e6-8815-7632b9ded21f.png)

Before spending too much time trying to get the (S)CSS perfect I thought it might be good to get feedback whether you actually wanted to include something like this.

Disadvantages: On big screens the pattern repeats (but I don't think that's a problem)

My changes are also on my fork ... let me know what you think!

**Comment by rufuspollock** [comment]
@rgieseke this would be great - and we'd definitely put it in.
