### ISSUE TITLE
Button name on homepage too long for mobile

### ISSUE THREAD

**Issue by schlos** [rgrp/cop21#6]
Button in index page:

<a href="{{ "/23-oct-2015/" | prepend: site.baseurl }}">Read the Draft Negotiating Text (23 Oct) (4th Dec coming soon)</a>

Is too long and not displayed well on mobile.

**Comment by schlos** [comment]
![quickmemo _2015-12-04-19-22-21](https://cloud.githubusercontent.com/assets/1014134/11597559/c1eb841c-9abc-11e5-9aa4-6503ee272adc.png)

**Comment by rufuspollock** [comment]
@schlos thanks - fixing now.

**Comment by rufuspollock** [comment]
FIXED. I believe! Thanks and if you would like to help more there's lots of easy things to do :-) #11

**Comment by schlos** [comment]
Hi!
I'm currently bind with other project, but will jump in when I'll be free. 

Great project!

Cheers,
Miroslav
